//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BODEGUERO
    {
        public int RUT_BODEG { get; set; }
        public string DV_BODEG { get; set; }
        public string PNOMBRE_BODEG { get; set; }
        public string SNOMBRE_BODEG { get; set; }
        public string APPATERNO_BODEG { get; set; }
        public string APMATERNO_BODEG { get; set; }
        public string SEXO_BODEG { get; set; }
        public string USUARIO_BODEG { get; set; }
        public string PASSWD_BODEG { get; set; }
        public string DIRECC_BODEG { get; set; }
        public short NRO_DIRECC_BODEG { get; set; }
        public int TELEFONO_BODEG { get; set; }
        public System.DateTime FECHA_NAC_BODEG { get; set; }
        public string CORREO_BODEG { get; set; }
    }
}
