//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
            this.RESERVA = new HashSet<RESERVA>();
            this.TARJETA = new HashSet<TARJETA>();
        }
    
        public int RUT_CLIENTE { get; set; }
        public string DV_CLIENTE { get; set; }
        public string PNOMBRE_CLIENTE { get; set; }
        public string SNOMBRE_CLIENTE { get; set; }
        public string APPATERNO_CLIENTE { get; set; }
        public string APMATERNO_CLIENTE { get; set; }
        public string SEXO_CLIENTE { get; set; }
        public string DIRECC_ADMIN { get; set; }
        public Nullable<short> NRO_DIRECC_CLIENTE { get; set; }
        public Nullable<int> TELEFONO_CLIENTE { get; set; }
        public Nullable<System.DateTime> FECHA_NAC_CLIENTE { get; set; }
        public string CORREO_CLIENTE { get; set; }
        public string MESA_ID_MESA { get; set; }
    
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
        public virtual ICollection<TARJETA> TARJETA { get; set; }
    }
}
