//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class COCINERO
    {
        public COCINERO()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public int RUT_COCINERO { get; set; }
        public string DV_COCINERO { get; set; }
        public string PNOMBRE_COCINERO { get; set; }
        public string SNOMBRE_COCINERO { get; set; }
        public string APPATERNO_COCINERO { get; set; }
        public string APMATERNO_COCINERO { get; set; }
        public string SEXO_COCINERO { get; set; }
        public string USUARIO_COCINERO { get; set; }
        public string PASSWD_COCINERO { get; set; }
        public string DIRECC_COCINERO { get; set; }
        public short NRO_DIRECC_COCINERO { get; set; }
        public int TELEFONO_COCINERO { get; set; }
        public System.DateTime FECHA_NAC_COCINERO { get; set; }
        public string CORREO_COCINERO { get; set; }
    
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
