//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMUNA
    {
        public COMUNA()
        {
            this.LOCAL = new HashSet<LOCAL>();
        }
    
        public string ID_COMUNA { get; set; }
        public string NOM_COMUNA { get; set; }
        public string REGION_ID_REGION { get; set; }
    
        public virtual REGION REGION { get; set; }
        public virtual ICollection<LOCAL> LOCAL { get; set; }
    }
}
