//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGREDIENTE
    {
        public INGREDIENTE()
        {
            this.RECETA2 = new HashSet<RECETA>();
        }
    
        public string ID_INGREDIENTE { get; set; }
        public string NOM_INGREDIENTE { get; set; }
        public short CANT_INGREDIENTE { get; set; }
        public string TIPO_INGREDIENTE { get; set; }
        public string RECETA_ID_RECETA { get; set; }
        public string BODEGA_ID_BODEGA { get; set; }
        public int PROVEEDOR_RUT_PROVEEDOR { get; set; }
        public string RECETA_ID_RECETA1 { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual RECETA RECETA { get; set; }
        public virtual RECETA RECETA1 { get; set; }
        public virtual ICollection<RECETA> RECETA2 { get; set; }
    }
}
