//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCAL
    {
        public LOCAL()
        {
            this.ADMINISTRADOR = new HashSet<ADMINISTRADOR>();
        }
    
        public string ID_LOCAL { get; set; }
        public string NOM_LOCAL { get; set; }
        public string DIRECC_LOCAL { get; set; }
        public int NRO_DIRECC { get; set; }
        public int TELEFONO_LOCAL { get; set; }
        public short CAPACIDAD_LOCAL { get; set; }
        public string COMUNA_ID_COMUNA { get; set; }
        public int ADMINISTRADOR_RUT_ADMIN { get; set; }
        public int ADMINISTRADOR_RUT_ADMIN1 { get; set; }
        public int ADMINISTRADOR_RUT_ADMIN2 { get; set; }
        public decimal ADMINISTRADORV1_RUT_ADMIN { get; set; }
    
        public virtual ICollection<ADMINISTRADOR> ADMINISTRADOR { get; set; }
        public virtual ADMINISTRADOR ADMINISTRADOR1 { get; set; }
        public virtual COMUNA COMUNA { get; set; }
    }
}
