//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        public PEDIDO()
        {
            this.CUENTA = new HashSet<CUENTA>();
        }
    
        public string ID_PEDIDO { get; set; }
        public System.DateTime FECHA_PEDIDO { get; set; }
        public string DESCRIPCION { get; set; }
        public int CLIENTE_RUT_CLIENTE { get; set; }
        public string PLATO_ID_PLATO { get; set; }
        public int COCINERO_RUT_COCINERO { get; set; }
        public int GARZON_RUT_GARZON { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual COCINERO COCINERO { get; set; }
        public virtual ICollection<CUENTA> CUENTA { get; set; }
        public virtual GARZON GARZON { get; set; }
        public virtual PLATO PLATO { get; set; }
    }
}
