//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLATO
    {
        public PLATO()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
            this.RECETA = new HashSet<RECETA>();
        }
    
        public string ID_PLATO { get; set; }
        public string NOM_PLATO { get; set; }
        public int PRECIO_PLATO { get; set; }
        public string DECRIP_PLATO { get; set; }
        public byte[] FOTO_PLATO { get; set; }
        public string CATEGORIA_ID_CATEG { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
        public virtual ICollection<RECETA> RECETA { get; set; }
    }
}
