//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public PROVEEDOR()
        {
            this.ENCARGO = new HashSet<ENCARGO>();
            this.INGREDIENTE = new HashSet<INGREDIENTE>();
        }
    
        public int RUT_PROVEEDOR { get; set; }
        public string DV_PROVEEDOR { get; set; }
        public string NOM_PROVEEDOR { get; set; }
        public string DIRECC_PROVEEDOR { get; set; }
        public int NRO_DIRECC_PROVEEDOR { get; set; }
        public int TELEFONO_PROVEEDOR { get; set; }
        public string CORREO_PROVEEDOR { get; set; }
    
        public virtual ICollection<ENCARGO> ENCARGO { get; set; }
        public virtual ICollection<INGREDIENTE> INGREDIENTE { get; set; }
    }
}
