//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARJETA
    {
        public long NRO_TARJETA { get; set; }
        public string TIPO_TARJETA { get; set; }
        public int SALDO_TARJETA { get; set; }
        public Nullable<System.DateTime> FECHA_EXP_TARJETA { get; set; }
        public Nullable<short> CODIGO_TARJETA { get; set; }
        public string BANCO_ID_BANCO { get; set; }
        public int CLIENTE_RUT_CLIENTE { get; set; }
    
        public virtual BANCO BANCO { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
