//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRADOR
    {
        public ADMINISTRADOR()
        {
            this.ENCARGO = new HashSet<ENCARGO>();
        }
    
        public string ID_ADMIN { get; set; }
        public int RUT_ADMIN { get; set; }
        public string DV_ADMIN { get; set; }
        public string PNOMBRE_ADMIN { get; set; }
        public string SNOMBRE_ADMIN { get; set; }
        public string APPATERNO_ADMIN { get; set; }
        public string APMATERNO_ADMIN { get; set; }
        public string SEXO_ADMIN { get; set; }
        public string USUARIO_ADMIN { get; set; }
        public string PASSWD_ADMIN { get; set; }
        public string DIRECC_ADMIN { get; set; }
        public short NRO_DIRECC_ADMIN { get; set; }
        public int TELEFONO_ADMIN { get; set; }
        public System.DateTime FECHA_NAC_ADMIN { get; set; }
        public string CORREO_ADMIN { get; set; }
        public string LOCAL_ID_LOCAL { get; set; }
    
        public virtual LOCAL LOCAL { get; set; }
        public virtual ICollection<ENCARGO> ENCARGO { get; set; }
    }
}
