//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJA
    {
        public CAJA()
        {
            this.CAJERO = new HashSet<CAJERO>();
        }
    
        public short ID_CAJA { get; set; }
        public string NOM_CAJA { get; set; }
    
        public virtual ICollection<CAJERO> CAJERO { get; set; }
    }
}
