//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJERO
    {
        public CAJERO()
        {
            this.CUENTA = new HashSet<CUENTA>();
        }
    
        public short ID_CAJERO { get; set; }
        public int RUT_CAJE { get; set; }
        public string DV_CAJE { get; set; }
        public string PNOMBRE_CAJE { get; set; }
        public string SNOMBRE_CAJE { get; set; }
        public string APPATERNO_CAJE { get; set; }
        public string APMATERNO_CAJE { get; set; }
        public string SEXO_CAJE { get; set; }
        public string USUARIO_CAJE { get; set; }
        public string PASSWD_CAJE { get; set; }
        public string DIRECC_CAJE { get; set; }
        public short NRO_DIRECC_CAJE { get; set; }
        public int TELEFONO_CAJE { get; set; }
        public System.DateTime FECHA_NAC_CAJE { get; set; }
        public string CORREO_CAJE { get; set; }
        public short ID_CAJA { get; set; }
    
        public virtual CAJA CAJA { get; set; }
        public virtual ICollection<CUENTA> CUENTA { get; set; }
    }
}
