//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIA
    {
        public CATEGORIA()
        {
            this.PLATO = new HashSet<PLATO>();
        }
    
        public string ID_CATEG { get; set; }
        public string DESCRIP_CATEG { get; set; }
        public string NOM_CATEG { get; set; }
    
        public virtual ICollection<PLATO> PLATO { get; set; }
    }
}
