//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public int ID_CLIENTE { get; set; }
        public string RUT_CLIENTE { get; set; }
        public string PASSWORD_CLIENTE { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string APELLIDO_CLIENTE { get; set; }
        public string CORREO_CLIENTE { get; set; }
        public Nullable<int> TELEFONO_CLIENTE { get; set; }
    
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
