//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA
    {
        public int CODIGO_CUENTA { get; set; }
        public System.DateTime FECHA_CUENTA { get; set; }
        public string METODO_PAGO_CUENTA { get; set; }
        public int MONTO_PAGAR_CUENTA { get; set; }
        public int IVA_CUENTA { get; set; }
        public int MONTO_TOTAL_CUENTA { get; set; }
        public int PEDIDO_ID_PEDIDO { get; set; }
        public short ID_CAJERO { get; set; }
    
        public virtual CAJERO CAJERO { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
    }
}
