//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GARZON
    {
        public GARZON()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public short ID_GARZON { get; set; }
        public int RUT_GARZON { get; set; }
        public string DV_GARZON { get; set; }
        public string PNOMBRE_GARZON { get; set; }
        public string SNOMBRE_GARZON { get; set; }
        public string APPATERNO_GARZON { get; set; }
        public string APMATERNO_GARZON { get; set; }
        public string SEXO_GARZON { get; set; }
        public string DIRECC_GARZON { get; set; }
        public short NRO_DIRECC_GARZON { get; set; }
        public int TELEFONO_GARZON { get; set; }
        public System.DateTime FECHA_NAC_GARZON { get; set; }
        public string CORREO_GARZON { get; set; }
    
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
