//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSUMO
    {
        public INSUMO()
        {
            this.PEDIDO_INSUMO = new HashSet<PEDIDO_INSUMO>();
            this.RECETA = new HashSet<RECETA>();
        }
    
        public short ID_INSUMO { get; set; }
        public string NOMBRE_INSUMO { get; set; }
        public short STOCK_INSUMO { get; set; }
        public string UNIDAD_MEDIDA_INSUMO { get; set; }
        public int PRECIO_INSUMO { get; set; }
    
        public virtual ICollection<PEDIDO_INSUMO> PEDIDO_INSUMO { get; set; }
        public virtual ICollection<RECETA> RECETA { get; set; }
    }
}
