//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLATO
    {
        public PLATO()
        {
            this.PEDIDO_PLATOS = new HashSet<PEDIDO_PLATOS>();
            this.RECETA = new HashSet<RECETA>();
        }
    
        public short ID_PLATO { get; set; }
        public string NOMBRE_PLATO { get; set; }
        public int PRECIO_PLATO { get; set; }
        public string DESCRIPCION_PLATO { get; set; }
        public Nullable<short> TIEMPO_PREPARACION { get; set; }
        public short TIPO_PLATO_ID_TIPO_PLATO { get; set; }
    
        public virtual ICollection<PEDIDO_PLATOS> PEDIDO_PLATOS { get; set; }
        public virtual TIPO_PLATO TIPO_PLATO { get; set; }
        public virtual ICollection<RECETA> RECETA { get; set; }
    }
}
