//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.ENCARGO = new HashSet<ENCARGO>();
            this.RECETA = new HashSet<RECETA>();
        }
    
        public short ID_PRODUCTO { get; set; }
        public string NOM_PRODUCTO { get; set; }
        public short CANT_PRODUCTO { get; set; }
        public string TIPO_PRODUCTO { get; set; }
        public short BODEGA_ID_BODEGA { get; set; }
        public int PROVEEDOR_RUT_PROVEEDOR { get; set; }
    
        public virtual BODEGA BODEGA { get; set; }
        public virtual ICollection<ENCARGO> ENCARGO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual ICollection<RECETA> RECETA { get; set; }
    }
}
