//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETA
    {
        public RECETA()
        {
            this.PLATO = new HashSet<PLATO>();
        }
    
        public int ID_RECETA { get; set; }
        public string NOM_RECETA { get; set; }
        public string DESCRIP_RECETA { get; set; }
        public short PRODUCTO_ID_PRODUCTO { get; set; }
    
        public virtual ICollection<PLATO> PLATO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
