//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGION
    {
        public REGION()
        {
            this.COMUNA = new HashSet<COMUNA>();
        }
    
        public string ID_REGION { get; set; }
        public string NOM_REGION { get; set; }
        public string ORDINAL_REGION { get; set; }
        public string PAIS_ID_PAIS { get; set; }
    
        public virtual ICollection<COMUNA> COMUNA { get; set; }
        public virtual PAIS PAIS { get; set; }
    }
}
