//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestauranteEntities : DbContext
    {
        public RestauranteEntities()
            : base("name=RestauranteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMINISTRADOR> ADMINISTRADOR { get; set; }
        public DbSet<BANCO> BANCO { get; set; }
        public DbSet<BODEGA> BODEGA { get; set; }
        public DbSet<BODEGUERO> BODEGUERO { get; set; }
        public DbSet<CAJA> CAJA { get; set; }
        public DbSet<CAJERO> CAJERO { get; set; }
        public DbSet<CATEGORIA> CATEGORIA { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<COCINERO> COCINERO { get; set; }
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<CUENTA> CUENTA { get; set; }
        public DbSet<ENCARGO> ENCARGO { get; set; }
        public DbSet<GARZON> GARZON { get; set; }
        public DbSet<LOCAL> LOCAL { get; set; }
        public DbSet<MESA> MESA { get; set; }
        public DbSet<PAIS> PAIS { get; set; }
        public DbSet<PEDIDO> PEDIDO { get; set; }
        public DbSet<PLATO> PLATO { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public DbSet<RECETA> RECETA { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<RESERVA> RESERVA { get; set; }
        public DbSet<TARJETA> TARJETA { get; set; }
    }
}
