//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PLATO
    {
        public TIPO_PLATO()
        {
            this.PLATO = new HashSet<PLATO>();
        }
    
        public short ID_TIPO_PLATO { get; set; }
        public string NOMBRE_TIPO_PLATO { get; set; }
    
        public virtual ICollection<PLATO> PLATO { get; set; }
    }
}
