//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public int ID_VENTA { get; set; }
        public int SUBTOTAL_VENTA { get; set; }
        public short IVA_VENTA { get; set; }
        public int PROPINA_VENTA { get; set; }
        public int TOTAL_VENTA { get; set; }
        public System.DateTime FECHA_VENTA { get; set; }
        public string TIPO_PAGO { get; set; }
        public int PEDIDO_ID_PEDIDO { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
    }
}
