// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class CrearPedidoTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void crearPedido() {
    driver.Navigate().GoToUrl("http://localhost:50386/");
    driver.Manage().Window.Size = new System.Drawing.Size(974, 1040);
    driver.FindElement(By.LinkText("ENTRAR")).Click();
    driver.FindElement(By.Id("rut")).Click();
    driver.FindElement(By.Id("rut")).SendKeys("195313923");
    driver.FindElement(By.Id("PASSWORD_CLIENTE")).Click();
    driver.FindElement(By.Id("PASSWORD_CLIENTE")).SendKeys("mat4242");
    driver.FindElement(By.CssSelector(".btn:nth-child(5)")).Click();
    driver.FindElement(By.LinkText("Agregar al pedido")).Click();
    Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Su pedido se ha agregado correctamente, dirijase a \'Carro\' para continuar."));
    driver.FindElement(By.LinkText("Carro")).Click();
    driver.FindElement(By.Id("idMesa")).Click();
    driver.FindElement(By.Id("idMesa")).Click();
    driver.FindElement(By.CssSelector(".btn-success")).Click();
    Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Su pedido se ha confirmado correctamente. Disfrute su comida."));
    driver.FindElement(By.LinkText("Ver Pedidos")).Click();
    driver.FindElement(By.LinkText("Pedir cuenta")).Click();
    Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Se ha generado la boleta, dirijase a Caja para pagar."));
    driver.FindElement(By.CssSelector(".col-lg-3:nth-child(6)")).Click();
  }
}
