// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;


[TestFixture]
public class WebPayTestTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void webPayTest() {
    // Test name: WebPayTest
    // Step # | name | target | value
    // 1 | open | /WebPay | 
    driver.Navigate().GoToUrl("https://localhost:44396/WebPay");
    // 2 | setWindowSize | 1936x1056 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
    // 3 | click | css=.btn | 
    driver.FindElement(By.CssSelector(".btn")).Click();
    // 4 | assertAlert | Se le redirigirá a la plataforma WebPay Plus para pagar | 
    Assert.That(driver.SwitchTo().Alert().Text, Is.EqualTo("Se le redirigirá a la plataforma WebPay Plus para pagar"));
    // 5 | click | css=.method:nth-child(3) | 
    driver.FindElement(By.CssSelector(".method:nth-child(3)")).Click();
    // 6 | click | id=visa-card-show | 
    driver.FindElement(By.Id("visa-card-show")).Click();
    // 7 | type | id=visa-card-show | 4051 8856 0044 6623
    driver.FindElement(By.Id("visa-card-show")).SendKeys("4051 8856 0044 6623");
    // 8 | click | id=fechaExpiracion | 
    driver.FindElement(By.Id("fechaExpiracion")).Click();
    // 9 | type | id=fechaExpiracion | 12/12
    driver.FindElement(By.Id("fechaExpiracion")).SendKeys("12/12");
    // 10 | type | id=password-invalid | 123
    driver.FindElement(By.Id("password-invalid")).SendKeys("123");
    // 11 | click | css=.button | 
    driver.FindElement(By.CssSelector(".button")).Click();
    // 12 | mouseOver | css=.button | 
    {
      var element = driver.FindElement(By.CssSelector(".button"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 13 | click | css=.button | 
    driver.FindElement(By.CssSelector(".button")).Click();
    // 14 | selectFrame | index=1 | 
    driver.SwitchTo().Frame(1);
    // 15 | type | id=rutClient | 11.111.111-1
    driver.FindElement(By.Id("rutClient")).SendKeys("11.111.111-1");
    // 16 | type | id=passwordClient | 123
    driver.FindElement(By.Id("passwordClient")).SendKeys("123");
    // 17 | click | css=td:nth-child(1) > input:nth-child(1) | 
    driver.FindElement(By.CssSelector("td:nth-child(1) > input:nth-child(1)")).Click();
    // 18 | click | css=td > input | 
    driver.FindElement(By.CssSelector("td > input")).Click();
    // 19 | selectFrame | relative=parent | 
    driver.SwitchTo().DefaultContent();
    // 20 | click | linkText=Ir a detalle de la compra | 
    driver.FindElement(By.LinkText("Ir a detalle de la compra")).Click();
  }
}
